import os

CONSUMER_KEY = os.environ['TWITTER_CONSUMER_KEY']
CONSUMER_SECRET = os.environ['TWITTER_CONSUMER_SECRET']
OAUTH_TOKEN = os.environ['TWITTER_ACCESS_TOKEN']
OAUTH_TOKEN_SECRET = os.environ['TWITTER_ACCESS_TOKEN_SECRET']
